name: manual deploy

on: [ workflow_dispatch ]

permissions:
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    concurrency: deployment
    outputs:
      aws_account: ${{ vars.AWS_ACCOUNT }}
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  deploy:
    concurrency: deployment
    needs: [ main ]
    uses: ./.github/workflows/deploy.yml
    with:
      aws_account: ${{ needs.main.outputs.aws_account }}
      project: backend
    secrets:
      amazon_client_secret: ${{ secrets.AMAZON_CLIENT_SECRET }}
      amplify_access_token: ${{ secrets.AMPLIFY_ACCESS_TOKEN }}
      facebook_client_secret: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
      google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      microsoft_oidc_client_secret: ${{ secrets.MICROSOFT_OIDC_CLIENT_SECRET }}
      nuxt_ui_pro_license: ${{ secrets.NUXT_UI_PRO_LICENSE }}