name: release

on: [ workflow_dispatch ]

permissions:
  contents: write
  id-token: write # needed for provenance data generation

env:
  NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      aws_account: ${{ vars.AWS_ACCOUNT }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - uses: fregante/setup-git-user@v2

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm nx release --skip-publish
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
